sudo: false

language: php
php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2

cache:
    directories:
        - $HOME/.composer/cache

before_install: phpenv config-rm xdebug.ini

install: composer install
