sudo: false

language: php
php:
    - 7.0
    - 7.1
    - 7.2
    - nightly

matrix:
    allow_failures:
        - php: nightly

cache:
    directories:
        - $HOME/.composer/cache

before_install: phpenv config-rm xdebug.ini

install: composer install
